// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApplicationTesting1.Migrations
{
    [DbContext(typeof(CityDataContext))]
    [Migration("20251027220334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("City.Models.CityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BluePrice")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GreenPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Humidity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RedPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Temperature")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YellowPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CityModel");
                });
#pragma warning restore 612, 618
        }
    }
}
